Sensedia/draft-openapi

automation-scripts/build.sh

A alteração se propõe a resolver o problema relacionado a não visualização dos nomes dos objetos no corpo da resposta dos endpoints na página do git pages.

FIX - Ajuste no script de build

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.csv
swagger-apis/credit-cards/2.0.0-RC1.0.yml
swagger-components/schemas/credit_cards_apis/CreditCardAccountsTransaction.yaml

feat(Cartão de crédito): ORB-1349 - Adicicionar pattern a campos AdditionalInfo

---

dictionary/accountsGetAccountsAccountIdTransactions_v2.csv
swagger-apis/accounts/2.0.0-RC1.0.yml
swagger-components/schemas/enum/EnumTransactionTypes.yaml

feat(Contas): ORB-1295 - Atualizar descrição da enum EnumTransactionTypes

---

dictionary/customersGetBusinessIdentifications_v2.csv
swagger-apis/customers/2.0.0-RC1.0.yml
swagger-apis/resources/index.html
swagger-components/schemas/customers_apis/BusinessContacts.yaml
swagger-components/schemas/customers_apis/BusinessIdentificationData.yaml
swagger-components/schemas/customers_apis/BusinessOtherDocument.yaml
swagger-components/schemas/customers_apis/PartiesParticipation.yaml

Campo | Ajuste
-- | --
companyCnpjNumber | Tornar o nome do campo plural, pois é uma lista.
otherDocuments | Dentro da estrutura todos os campos obrigatórios menos o expirationDate.
parties/shareholding | Alterar pra condicional Inserir restrição: [Restrição]: Campo obrigatório caso o type for igual a SOCIO e este tiver participação societária maior que 25%.
parties/documentExpirationDate | Tornar opcional
contacts | phones manter obrigatório, porém mudar o minItem = 0, O mesmo tratamento para o objeto e-mail

fix(Dados Cadastrais): ORB-1413 - Ajustes em Customers /business/identifications

---

dictionary/invoiceFinancingsGetContractsContractId_v2.csv
dictionary/loansGetContractsContractId_v2.csv
swagger-apis/invoice-financings/2.0.0-RC1.0.yml
swagger-apis/loans/2.0.0-RC1.0.yml
swagger-components/schemas/invoice_financings_apis/InvoiceFinancingsContractedFee.yaml
swagger-components/schemas/loans_apis/LoansFinancingsContractedFee.yaml

fix(Loans | Invoice Financings): ORB-1505 - Ajustar descrição do campo feeRate

---

swagger-apis/unarranged-accounts-overdraft/2.0.0-RC1.0.yml
swagger-components/schemas/business_commons/UnarrangedAccountOverdraftBalloonPaymentAmount.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/ResponseUnarrangedAccountOverdraftContract.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/ResponseUnarrangedAccountOverdraftContractList.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/ResponseUnarrangedAccountOverdraftInstalments.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/ResponseUnarrangedAccountOverdraftPayments.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/ResponseUnarrangedAccountOverdraftWarranties.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftBalloonPayment.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftChargeOverParcel.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftCompletedPayment.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftContractData.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftContractInterestRate.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftContractListData.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftContractedFee.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftFeeOverParcel.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftFinanceCharge.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftInstalmentsData.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftNonRegulatedCharge.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftOverParcel.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftPayment.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftPaymentsData.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftReleases.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftTaxesOverParcel.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftWarranty.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountsOverdraftContractedWarranty.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountsOverdraftReleases.yaml

feat(OC_Adiantamento a Depositantes): ORB-1566 - Alterar additionalProperties para true

---

swagger-apis/loans/2.0.0-RC1.0.yml
swagger-components/_loans_apis_part.yml

fix(OC_Empréstimos): ORB-1653 - Incluir informação de paginação no endpoint de /payments

---

dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.csv
swagger-apis/credit-cards/2.0.0.yml
swagger-components/schemas/credit_cards_apis/CreditCardsAvailableAmount.yaml

fix(Cartão de Crédito): ORB-1695 - Alterar os campos para condicional com restrição

---

swagger-apis/financings/2.0.0.yml
swagger-components/schemas/financings_apis/FinancingsListContract.yaml

Reverts Sensedia/draft-openapi#324

Revert "fix(OC_Financiamento): ORB-1701 - Adicionar minLength no contractId"

---

dictionary/financingsGetContracts_v2.csv
swagger-apis/financings/2.0.0.yml
swagger-components/schemas/financings_apis/ResponseFinancingsContractList.yaml

Reverts Sensedia/draft-openapi#322

Revert "fix(financings): ORB-1700 - Ajustes na descriçaõ do elemento DATA"

---

swagger-apis/financings/2.0.0.yml
swagger-components/_financings_apis_part.yml

Reverts Sensedia/draft-openapi#320

Revert "fix(Financings): ORB-1698 - Ajustes de descrição no endpoint"

---

.gitignore

Fix - Commit vazio ->  .gitignore

Fix - Commit vazio ->  .gitignore

---

.github/workflows/build-and-deploy.yml

Fix - Adicionando espaço vazio

Fix - Adicionando espaço vazio

---

.github/workflows/build-and-deploy.yml

Fix - Commit Vazio

---

dictionary/financingsGetContractsContractId_v2.csv
dictionary/invoiceFinancingsGetContractsContractId_v2.csv
dictionary/loansGetContractsContractId_v2.csv
dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.csv
swagger-apis/financings/2.0.0.yml
swagger-apis/invoice-financings/2.0.0.yml
swagger-apis/loans/2.0.0.yml
swagger-apis/unarranged-accounts-overdraft/2.0.0.yml
swagger-components/schemas/financings_apis/FinancingsContract.yaml
swagger-components/schemas/invoice_financings_apis/InvoiceFinancingsContract.yaml
swagger-components/schemas/loans_apis/LoansFinancingsContract.yaml
swagger-components/schemas/unarranged_account_overdraft_apis/UnarrangedAccountOverdraftContractData.yaml

feat(Operações de Crédito): ORB-1731 - Ajustar descrição do array interestRates

---

dictionary/financingsGetContractsContractIdPayments_v2.csv
swagger-apis/financings/2.0.1.yml
swagger-components/schemas/financings_apis/FinancingsReleases.yaml

PR aberto para adição do código de solicitação ao commit

fix(OC_Financiamentos)[S130]: ORB-1759 - Alterar mandatoriedade do campo installmentId

---

dictionary/paymentsGetPixPaymentsPaymentId_v2.csv
dictionary/paymentsPostPixPayments_v2.csv
swagger-apis/payments/2.0.0.yml
swagger-components/schemas/enum/EnumPaymentStatusType.yaml

feat(Pagamentos): ORB-1932 - [P55] - Adicionar status SCHD à máquina de estados do Pagamento

---

dictionary/investmentsGetTreasure_v1.csv
swagger-apis/investments/1.0.0-rc2.0.yml
swagger-components/schemas/investments_apis/InvestmentsParticipant.yaml
swagger-components/schemas/investments_apis/InvestmentsTreasure.yaml

fix(Investimentos): ORB-2171- PC23 - Isolar os componentes e ajustar o pattern dos seguintes campos na API de Investimentos:
​/treasure-titles/data/participant/brand
​/treasure-titles/data/participant/name

[ORB-2171][PC23] [Investment] [​treasure-titles] Pattern - Ajustes

---

dictionary/getBusinessAcquiringServices_v1.csv
dictionary/getPersonalAcquiringServices_v1.csv
swagger-apis/acquiring-services/1.0.0-rc2.0.yml
swagger-components/schemas/acquiring_services_apis/AcquiringParticipant.yaml

…Array de objeto “urlComplementaryList”

feat(acquiring-services): ORB-2225 - PC26 - Adicionar a descrição no Array de objeto “urlComplementaryList”

---

swagger-components/_bank_fixed_incomes_apis_part.yml

Fazendo o PR pra levar as alterações para homologação

Adição de espaços para melhor visualização

---

dictionary/getPensionRiskCoverages_v1.csv
swagger-apis/pension/1.0.0-rc2.0.yml
swagger-components/schemas/pension_apis/risk/GetRiskPensionContractData.yaml
swagger-components/schemas/pension_apis/risk/RiskPensionCoverage.yaml

fix(Pension): ORB-2379 - PC48 - Alterar para opcional

---

dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
dictionary/creditFixedIncomesGetInvestments_v1.csv
swagger-apis/credit-fixed-incomes/1.0.0-rc1.0.yml
swagger-components/schemas/credit_fixed_incomes_apis/ResponseCreditFixedIncomesProductList.yaml
swagger-components/schemas/credit_fixed_incomes_apis/ResponseCreditFixedIncomesTransactions.yaml
swagger-components/schemas/credit_fixed_incomes_apis/ResponseCreditFixedIncomesTransactionsCurrent.yaml

feat(Credit Fixed Incomes): ORB-2393 - PA34 - Escopo complementar - terceira onda

---

dictionary/getPensionRiskCoverages_v1.csv
swagger-apis/pension/1.0.0-rc2.0.yml
swagger-components/_pension_apis_part.yml
swagger-components/schemas/pension_apis/risk/RiskPensionCoverageAttributes.yaml
swagger-components/schemas/pension_apis/risk/RiskPensionEnumProfitModality.yaml

fix(Pension): ORB-2440 - PC52 - profitModality

---

dictionary/getPensionSurvivalCoverages_v1.csv
swagger-apis/pension/1.0.0-rc2.0.yml
swagger-components/schemas/pension_apis/survival/GetSurvivalPensionContractData.yaml
swagger-components/schemas/pension_apis/survival/SurvivalPensionDefferalPeriod.yaml

fix(Pension): ORB-2443 - PC54 - Mandatoriedade - opcional

---

dictionary/getPensionSurvivalCoverages_v1.csv
swagger-apis/pension/1.0.0-rc2.0.yml
swagger-components/schemas/enum/EnumPensionUpdateIndex.yaml

fix(Pension): ORB-2451 - PC55 - enum - add NAO_SE_APLICA

---

dictionary/getPensionSurvivalCoverages_v1.csv
swagger-apis/pension/1.0.0-rc2.0.yml
swagger-components/_pension_apis_part.yml
swagger-components/schemas/pension_apis/survival/GetSurvivalPensionContractData.yaml
swagger-components/schemas/pension_apis/survival/SurvivalPensionEnumTargetAudience.yaml

fix(Pension): ORB-2453 - PC55 - targetAudience - ajustar enum

---

dictionary/getPensionRiskCoverages_v1.csv
swagger-apis/pension/1.0.0-rc2.0.yml
swagger-components/_pension_apis_part.yml
swagger-components/schemas/pension_apis/risk/RiskPensionEnumGracePeriodUnit.yaml
swagger-components/schemas/pension_apis/risk/RiskPensionGracePeriod.yaml
swagger-components/schemas/pension_apis/risk/RiskPensionReclaim.yaml

fix(Pension): ORB-2447 - PC59 - gracePeriod

---

dictionary/getPensionSurvivalCoverages_v1.csv
swagger-apis/pension/1.0.0-rc2.0.yml
swagger-components/schemas/pension_apis/survival/GetSurvivalPensionContractData.yaml

fix(Pension): ORB-2445 - PC57 - modality - obrigatório

---

dictionary/getPensionRiskCoverages_v1.csv
swagger-apis/pension/1.0.0-rc2.0.yml
swagger-components/_pension_apis_part.yml
swagger-components/schemas/pension_apis/risk/RiskPensionCoverageAttributes.yaml

fix(Pension): ORB-2448 - PC60 - gracePeriod - criar objeto

---

dictionary/FundsGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
dictionary/FundsGetInvestmentsInvestmentIdTransactions_v1.csv
swagger-apis/funds/1.0.0-rc1.0.yml
swagger-components/_funds_apis_part.yml
swagger-components/schemas/funds_apis/EnumFundsTransactionsCurrentTransactionType.yaml
swagger-components/schemas/funds_apis/EnumFundsTransactionsCurrentType.yaml
swagger-components/schemas/funds_apis/EnumFundsTransactionsTransactionType.yaml
swagger-components/schemas/funds_apis/EnumFundsTransactionsType.yaml
swagger-components/schemas/funds_apis/ResponseFundsTransactions.yaml
swagger-components/schemas/funds_apis/ResponseFundsTransactionsCurrent.yaml
swagger-components/schemas/funds_apis/ResponseFundsTransactionsCurrentData.yaml
swagger-components/schemas/funds_apis/ResponseFundsTransactionsData.yaml

feat(Funds): ORB-2479 - PA33 - Criar endpoint de Movimentação recente do produto

---

dictionary/getPersonalInsurance_v1.csv
swagger-apis/insurances/1.0.0-rc2.0.yml
swagger-components/_insurances_apis_part.yml
swagger-components/schemas/insurances_apis/InsuranceBenefitRecalculation.yaml
swagger-components/schemas/insurances_apis/personal/PersonalCoverageItem.yaml
swagger-components/schemas/insurances_apis/personal/PersonalCoverageItemAttributes.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceData.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceGracePeriod.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceMinimumRequirement.yaml

feat(Insurances): ORB-2498 - PC67 - Seguros - tornar campos opcionais

---

dictionary/getPersonalInsurance_v1.csv
swagger-apis/insurances/1.0.0-rc2.0.yml
swagger-components/_insurances_apis_part.yml
swagger-components/schemas/insurances_apis/InsuranceBenefitRecalculation.yaml
swagger-components/schemas/insurances_apis/personal/PersonalCoverageItem.yaml
swagger-components/schemas/insurances_apis/personal/PersonalCoverageItemAttributes.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceData.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceGracePeriod.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceMinimumRequirement.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceReclaim.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceReclaimTableItem.yaml

feat(Insurances): ORB-2499 - PC70 - Seguros - Alterar para obrigatório

---

dictionary/getPersonalInsurance_v1.csv
swagger-apis/insurances/1.0.0-rc2.0.yml
swagger-components/_insurances_apis_part.yml
swagger-components/schemas/insurances_apis/InsuranceBenefitRecalculation.yaml
swagger-components/schemas/insurances_apis/personal/PersonalCoverageItem.yaml
swagger-components/schemas/insurances_apis/personal/PersonalCoverageItemAttributes.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceData.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceGracePeriod.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceMinimumRequirement.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceReclaim.yaml
swagger-components/schemas/insurances_apis/personal/PersonalInsuranceReclaimTableItem.yaml

feat(Insurances): ORB-2500 - PC70 - Seguros - Alterar para opcional

---

dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
swagger-apis/credit-fixed-incomes/1.0.0-rc1.0.yml
swagger-apis/credit-fixed-incomes/1.0.0-rc2.0.yml
swagger-components/schemas/credit_fixed_incomes_apis/CreditFixedIncomesTransactionsCurrent.yaml

fix(Credit Fixed Incomes): ORB-2516 - PA56 - Alterar nome de campo

---

swagger-apis/webhook/1.0.0.yml
swagger-apis/webhook/index.html

feat(webhook): ORB-2556 - PB29 - Criar estrutura inicial da api de webhook

---

dictionary/capitalizationBondsGetProducts_vx.csv
swagger-apis/capitalization-bonds/index.html
swagger-apis/capitalization-bonds/x.x.x.yml

feat(Capitalization Bonds): ORB-2576 - PC81 - Tipo ENUM aceitar NA

---

dictionary/getPensionRiskCoverages_vx.csv
dictionary/getPensionSurvivalCoverages_vx.csv
swagger-apis/pension/x.x.x.yml

feat(Pension): ORB-2584 - PC81 - Tornar campos tipo boolean opcionais

---

swagger-apis/webhook/1.0.0-beta1.yml

feat(Webhook): ORB-2597 - SP29 - Ajustes pós homologação 2

---

dictionary/getPersonalInsurance_vx.csv
swagger-apis/insurances/index.html
swagger-apis/insurances/x.x.x.yml

feat(Insurance): ORB-2589 - PC81 - Tornar campos tipo boolean opcionais

---

swagger-apis/webhook/1.0.0-beta1.yml

**Fix(WebHook)** 
- Ajustando texto em orientações gerais

 GT - Serviços - Fix(WebHook) - Ajustando texto em orientações gerais

---

swagger-apis/webhook/1.0.0-beta1.yml

**Fix(WebHook)** 
-  Adicionando novos textos em orientações gerais

GT - Serviços - Fix(WebHook) - Adicionando novos textos em orientações gerais

---

swagger-apis/exchanges-aguardando-definicao/1.0.0-rc1.0.yml
swagger-apis/exchanges-aguardando-definicao/index.html

feat(Exchanges): ORB-2602 - PA69 - PA70 - PA71 - Criar endpoint de Listagem dos produtos

---

dictionary/getPersonalInsurance_v1.csv
swagger-apis/insurances/1.0.0-rc3.0.yml

fix(Insurances): ORB-2639 - PC81 - Percentuais - Ajuste

---

dictionary/exchangesGetOperationsOperationIdEvents_v1.csv
dictionary/exchangesGetOperationsOperationId_v1.csv
swagger-apis/exchanges/1.0.0-rc1.0.yml

feat(Exchanges): ORB-2687 - PA69 - Melhoria - Padronizar restrições dos campos da API

---

dictionary/capitalizationBondsGetProducts_v1.csv
swagger-apis/capitalization-bonds/1.0.1.yml
swagger-apis/capitalization-bonds/index.html

feat(Capitalization Bonds): ORB-2716 - PA85 - Remover o maxLength

---

dictionary/creditFixedIncomesGetInvestmentsInvestmentId_v1.csv
swagger-apis/credit-fixed-incomes/1.0.0-rc2.0.yml

feat(Credit Fixed Incomes): ORB-2724 - PA99 - Ajustar propriedades de campos

---

swagger-apis/products-services/y.y.y.yml

feat(Products-Servisec): ORB-2713- PC86 - Remover maxItems

---

swagger-apis/products-services/index.html
swagger-apis/products-services/y.y.y.yml

feat(Products-Services): ORB-2710- PC88 - Links

---

swagger-apis/products-services/index.html
swagger-apis/products-services/y.y.y.yml

feat(Products-Services): ORB-2711- PC89 - Remover resquicio

---

swagger-apis/payments/2.1.0.yml

feat(Payments): ORB-2800 - PB56 - Realizar ajustes

---

swagger-apis/payments/2.1.0.yml

feat(Payments): ORB-2802 - PB57 - Realizar ajustes

---

swagger-apis/payments/2.1.0.yml

feat(Payments): ORB-2804 - PB58 - Realizar ajustes

---

dictionary/paymentsGetConsentsConsentId_v2.csv
dictionary/paymentsPostConsents_v2.csv
swagger-apis/payments/2.1.0.yml

feat(Payments): ORB-2806 - PB59 - Realizar ajustes

---

swagger-apis/payments/2.1.0.yml

feat(Payments): ORB-2808 - PB60 - Realizar ajustes

---

swagger-apis/products-services/y.y.y.yml

feat(Products and Services): ORB-2792 - PC91 - Criar Https response errors 

---

swagger-apis/products-services/y.y.y.yml

feat(Products and Services): ORB-2793 - PC92 - Incluir propriedade maxItems

---

swagger-apis/products-services/y.y.y.yml

feat(Products and Services): ORB-2795 - PC94 - Remover maxItems e minItens

---

swagger-apis/products-services/y.y.y.yml

feat(Products and Services): ORB-2796 - PC95 - Incluir maxItens

---

dictionary/paymentsGetPixPaymentsPaymentId_v3.csv
dictionary/paymentsPatchPixPaymentsPaymentId_v3.csv
dictionary/paymentsPostPixPayments_v3.csv
swagger-apis/payments/3.0.0-beta.1.yml

feat(Payments): ORB-2728 - PB46 - Incluir novo ENUM no rejectionReason code de Payments

---

dictionary/paymentsGetPixPaymentsPaymentId_v3.csv
dictionary/paymentsPatchPixPaymentsPaymentId_v3.csv
dictionary/paymentsPostPixPayments_v3.csv
swagger-apis/payments/3.0.0-beta.1.yml

feat(Payments): ORB-2715 - PB53 - Remover Enums dos http erros 422

---

dictionary/paymentsGetConsentsConsentId_v3.csv
dictionary/paymentsGetPixPaymentsPaymentId_v3.csv
dictionary/paymentsPatchPixPaymentsPaymentId_v3.csv
dictionary/paymentsPostPixPayments_v3.csv
swagger-apis/payments/3.0.0-beta.1.yml

feat(Payments): ORB-2713 - PB50 - Incluir objeto complexo de rejectionReason em Consent Payments

---

dictionary/paymentsGetConsentsConsentId_v3.csv
swagger-apis/payments/3.0.0-beta.1.yml

feat(Payments): ORB-2718 - PB64 - Incluir descrição de campo

---

dictionary/getBusinessAccounts_vy.csv
dictionary/getBusinessUnarrangedAccountOverdraft_vy.csv
dictionary/getPersonalAccounts_vy.csv
swagger-apis/products-services/y.y.y.yml

feat(Products and Services): ORB-2871 - PC122 - Ratificação PC92 e PC95

---

dictionary/getBusinessAccounts_vy.csv
dictionary/getPersonalAccounts_vy.csv
dictionary/getPersonalUnarrangedAccountOverdraft_vy.csv
swagger-apis/products-services/y.y.y.yml

feat(Products and Services): ORB-2869 - PC120 - personal-unarranged-account-overdraft - maxItem

---

swagger-apis/credit-fixed-incomes/1.0.0-rc3.0.yml
swagger-apis/credit-fixed-incomes/index.html

feat(Credit Fixed Incomes): ORB-2885 - PA100 - Ajustar descrição do endpoint balances

---

swagger-apis/bank-fixed-incomes/1.0.0-rc3.0.yml
swagger-apis/bank-fixed-incomes/index.html

feat(Bank Fixed Incomes): ORB-2889 - PA100 - Ajustar descrição do endpoint balances

---

dictionary/getPensionRiskCoverages_v1.csv
dictionary/getPensionSurvivalCoverages_v1.csv
swagger-apis/pension/1.0.1.yml
swagger-apis/pension/index.html

feat(Pension): ORB-2895 - PC105 - remover maxLength dos enums

---

dictionary/getPersonalInsurance_v1.csv
swagger-apis/insurances/1.0.1.yml

feat(Insurance): ORB-2856 - PC107 - alterações em differenciatedPercentage

---

swagger-apis/payments/3.0.0-beta.1.yml

feat(Payments): ORB-2897 - SB31 - Atualizar header da API - Melhoria

---

dictionary/paymentsGetConsentsConsentId_v3.csv
dictionary/paymentsGetPixPaymentsPaymentId_v3.csv
dictionary/paymentsPatchPixPaymentsPaymentId_v3.csv
dictionary/paymentsPostConsents_v3.csv
dictionary/paymentsPostPixPayments_v3.csv
swagger-apis/payments/3.0.0-beta.2.yml

feat(Payments): ORB-2900 - PB71 - Incluir enum em campo

---

dictionary/paymentsGetConsentsConsentId_v3.csv
dictionary/paymentsGetPixPaymentsPaymentId_v3.csv
dictionary/paymentsPatchPixPaymentsPaymentId_v3.csv
dictionary/paymentsPostConsents_v3.csv
dictionary/paymentsPostPixPayments_v3.csv
swagger-apis/payments/3.0.0-beta.2.yml

feat(Payments): ORB-2901 - PB73 - Adicionar descrição no header da API

---

dictionary/paymentsGetConsentsConsentId_v3.csv
dictionary/paymentsGetPixPaymentsPaymentId_v3.csv
dictionary/paymentsPatchPixPaymentsPaymentId_v3.csv
dictionary/paymentsPostConsents_v3.csv
dictionary/paymentsPostPixPayments_v3.csv
swagger-apis/payments/3.0.0-beta.2.yml

feat(Payments): ORB-2902 - PB74 - Adicionar a descrição do campo

---

dictionary/creditFixedIncomesGetInvestmentsInvestmentIdBalances_v1.csv
dictionary/creditFixedIncomesGetInvestmentsInvestmentId_v1.csv
swagger-apis/credit-fixed-incomes/1.0.0-rc3.0.yml

feat(Credit Fixed Incomes): ORB-2938 - PA107 - Alterar mandatoriedade e descrição de campos

---

dictionary/treasureTitlesGetInvestmentsInvestmentIdBalances_v1.csv
dictionary/treasureTitlesGetInvestmentsInvestmentId_v1.csv
swagger-apis/treasure-titles/1.0.0-rc3.0.yml

feat(Treasure titles): ORB-2973 - PA121 - Alterar descrição de campo

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdBills_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountId_v2.csv
dictionary/creditCardsGetAccounts_v2.csv
swagger-apis/credit-cards/2.1.0-rc.1.yml

feat(Credit Cards): ORB-3006 - PA118 - Alterar propriedade do campo transactionName

---

dictionary/unarrangedAccountsOverdraftGetContractsContractIdPayments_v2.csv
dictionary/unarrangedAccountsOverdraftGetContractsContractIdScheduledInstalments_v2.csv
dictionary/unarrangedAccountsOverdraftGetContractsContractIdWarranties_v2.csv
dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.csv
dictionary/unarrangedAccountsOverdraftGetContracts_v2.csv
swagger-apis/unarranged-accounts-overdraft/2.1.0-rc.1.yml
swagger-apis/unarranged-accounts-overdraft/2.1.1-rc.1.yml
swagger-apis/unarranged-accounts-overdraft/index.html

Propostas contempladas nesse pull request
- PA110 
- PA115
-  PA117

GT Dados do cliente: Feat(Unarranged account overdraft): PA110 - PA115 - PA117

---

dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.csv
swagger-apis/credit-cards/2.1.0-rc.1.yml

feat(Credit Cards): ORB-3060 - PA127 - Novo campo

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.csv
swagger-apis/credit-cards/2.1.0-rc.1.yml

feat(Credit Cards): ORB-3062 - PA128 - chargeIdentificator - alterações

---

dictionary/loansGetContractsContractId_v2.csv
swagger-apis/loans/2.1.0-rc.1.yml

feat(Loans): ORB-3067 - PA130 - CET - Descrição

---

swagger-apis/payments/3.0.0-beta.3.yml
swagger-apis/payments/index.html

feat(Payments): ORB-3078 - SB41 - Alterar descrição API

---

dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.csv
swagger-apis/credit-cards/2.1.0-rc.1.yml

feat(Credit Cards): ORB-3075 - PA134 - Resquício - usedAmountCurrency

---

dictionary/resourcesGetResources_v2.csv
swagger-apis/resources/2.1.0.yml
swagger-apis/resources/index.html

feat(Resources): ORB-3093 - PA137 - Complementar a descrição do campo

---

dictionary/accountsGetAccountsAccountIdBalances_v2.csv
dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.csv
dictionary/accountsGetAccountsAccountIdTransactions_v2.csv
swagger-apis/accounts/2.1.0-rc.1.yml

feat(Accounts): ORB-3103 - PA140 - Complemento da descrição com um caso de exceção de envio da contraparte do campo partieCnpjCpf

---

dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
swagger-apis/bank-fixed-incomes/1.0.0.yml
swagger-apis/bank-fixed-incomes/index.html

feat(Bank Fixed Incomes): ORB-3166 - Ajuste de valor de minlength

---

dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactions_v1.csv
dictionary/treasureTitlesGetInvestmentsInvestmentId_v1.csv
swagger-apis/treasure-titles/1.0.0.yml
swagger-apis/treasure-titles/index.html

feat(Treasure Titles): ORB-3167 - Ajuste de valor de minlength

---

dictionary/banktFixedIncomesGetInvestmentsInvestmentIdBalances_v1.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
swagger-apis/bank-fixed-incomes/1.0.0.yml
swagger-apis/bank-fixed-incomes/index.html

feat(Bank Fixed Incomes): ORB-3168 - PA148 - Ajustar descrição do campo

---

dictionary/treasureTitlesGetInvestmentsInvestmentIdBalances_v1.csv
dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactions_v1.csv
dictionary/treasureTitlesGetInvestmentsInvestmentId_v1.csv
swagger-apis/treasure-titles/1.0.0.yml
swagger-apis/treasure-titles/index.html

feat(Treasure Titles): ORB-3171 - PA148 - Ajustar descrição do campo

---

dictionary/paymentsGetConsentsConsentId_v3.csv
swagger-apis/payments/3.0.0-beta.3.yml

feat(Payments): ORB-3209 - PB80 - Inserir restrição

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.csv
swagger-apis/credit-cards/2.1.0-rc.1.yml

feat(Credit Cards): ORB-3190 - PA151 - faturas - transactionId

---

dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.csv
dictionary/accountsGetAccountsAccountIdTransactions_v2.csv
swagger-apis/accounts/2.1.0-rc.1.yml

feat(Accounts): ORB-3193 - PA152 - transactionId - mandatoriedade

---

dictionary/getEnrollment_v1.csv
dictionary/postEnrollments_v1.csv
swagger-apis/enrollments/ 1.0.0-rc.1.yml
swagger-apis/enrollments/index.html

feat(Enrollments): ORB-3280 - PS21 -Criar objeto fidoAssertion

---

dictionary/getBusinessAccounts_v1.csv
dictionary/getPersonalAccounts_v1.csv
swagger-apis/opendata-accounts/1.0.0-beta.1.yml
swagger-apis/opendata-accounts/index.html

feat(Opendata Accounts): ORB-3113 - PC131 - patterns - Alterar patterns

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.csv
swagger-apis/credit-cards/2.1.0-rc.2.yml
swagger-apis/credit-cards/index.html

feat(Credit Cards): ORB-3369 - PA07 - Ajustar propriedades do campo chargeIdentificator

---

swagger-apis/bank-fixed-incomes/1.0.1.yml
swagger-apis/bank-fixed-incomes/index.html

feat(Bank Fixed Incomes): ORB-3381 - PDC163 - Adicionar campo last no objeto de paginação links 

---

swagger-apis/variable-incomes/1.0.1.yml
swagger-apis/variable-incomes/index.html

feat(Variable Incomes): ORB-3395 - PDC163 - Adicionar campo last no objeto de paginação links 

---

swagger-apis/credit-fixed-incomes/1.0.1.yml

feat(Credit Fixed Incomes): ORB-3388 - PDC163 - Adicionar campo last no objeto de paginação links 

---

swagger-apis/treasure-titles/1.0.1.yml
swagger-apis/treasure-titles/index.html

feat(Treasure Titles): ORB-3402 - PDC163 - Adicionar campo last no objeto de paginação links 

---

swagger-apis/funds/1.0.1.yml
swagger-apis/funds/index.html

feat(Funds): ORB-3409 - PDC163 - Adicionar campo last no objeto de paginação links 

---

dictionary/getBusinessAccounts_v1.csv
dictionary/getPersonalAccounts_v1.csv
swagger-apis/opendata-accounts/1.0.0-beta.1.yml

depends on https://github.com/Sensedia/draft-openapi/pull/2187

feat(OD Accounts): ORB-3435 - PC148 - Alteração estrutura payload

---

dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.csv
dictionary/accountsGetAccountsAccountIdTransactions_v2.csv
swagger-apis/accounts/2.1.0-rc.2.yml
swagger-apis/accounts/index.html

fix(Accounts): ORB-3434 - PA124 - Incluir campo transactionDate nos dois endpints de transação

---

swagger-apis/enrollments/1.0.0-rc.2.yml
swagger-apis/enrollments/index.html

feat(Enrollments): ORB-3465 - PJR27 - Incluir campo e scope no endpoint - v1.0.0-rc.2

---

dictionary/consentsGetConsentsConsentId_v2.csv
dictionary/consentsPostConsents_v2.csv
swagger-apis/consents/2.2.0.yml
swagger-apis/consents/index.html

feat(Consents): ORB-3545 - PSR05 - Alterar descrição de campos

---

dictionary/paymentsPostPixPayments_v3.csv
swagger-apis/payments/3.0.0-rc.2.yml
swagger-apis/payments/index.html

feat(payments): ORB-3560 - PSV90 - Alterar descrição do HTTP 422 do endpoint patch_pix_payments

---

dictionary/consentsGetConsentsConsentId_v2.csv
dictionary/consentsPostConsentsConsentIdExtends_v2.csv
dictionary/consentsPostConsents_v2.csv
swagger-apis/consents/2.2.0.yml
swagger-apis/consents/index.html

feat(Consents): ORB-3540 - PSR02 - PSR03 - Criar Endpoint POST consents_extends

---

automation-scripts/dictionary_generator
dictionary/getBankingAgents_v2.csv
dictionary/getBranches_v2.csv
dictionary/getElectronicChannels_v2.csv
dictionary/getPhoneChannels_v2.csv
dictionary/getSharedAutomatedTellerMachines_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml
swagger-apis/channels/index.html

feat(Channels): ORB-3553 - PDA165 - countryCode​ - Alterações

---

swagger-apis/enrollments/1.0.0.yml
swagger-apis/enrollments/1.1.0.yml
swagger-apis/enrollments/index.html

feat(Enrollments): ORB-3572 - PJR29 - Nova versão

---

swagger-apis/credit-cards/2.1.0-rc.3.yml
swagger-apis/credit-cards/index.html

feat(Credit Cards): ORB-3599 - SPA150 - Incluir e Atualizar textos no header da API

---

dictionary/consentsGetConsentsConsentId_v3.csv
swagger-apis/consents/3.0.0-beta.1.yml

feat(Consents): ORB-3606 - PDC170 -  Ajustar propriedade do campo additionalInformation

---

dictionary/getBusinessAccounts_v1.csv
dictionary/getPersonalAccounts_v1.csv
swagger-apis/opendata-accounts/1.0.0-beta.1.yml

feat(Opendata Accounts): ORB-3625 - PDA181 - savingAccount - Ajustar descrição

---

swagger-apis/consents/2.2.0-beta.1.yml

Segundo ajuste no status code 422 details

GT Dados do cliente: FIX(Consents): Segundo ajuste no status code 422 details

---

dictionary/getBankingAgents_v2.csv
dictionary/getBranches_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml

feat(Channels): ORB-3618 - PDA174 - Reestruturação de payload

---

dictionary/getBankingAgents_v2.csv
dictionary/getBranches_v2.csv
dictionary/getElectronicChannels_v2.csv
dictionary/getPhoneChannels_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml

feat(Channels): ORB-3620 - PDA176 - Reestruturação de payload

---

dictionary/getBankingAgents_v2.csv
dictionary/getBranches_v2.csv
dictionary/getElectronicChannels_v2.csv
dictionary/getPhoneChannels_v2.csv
dictionary/getSharedAutomatedTellerMachines_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml

feat(Channels): ORB-3621 - PDA177 - Reestruturação de payload

---

dictionary/getBankingAgents_v2.csv
dictionary/getBranches_v2.csv
dictionary/getElectronicChannels_v2.csv
dictionary/getPhoneChannels_v2.csv
dictionary/getSharedAutomatedTellerMachines_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml

feat(Channels): ORB-3624 - PDA180 - contryCode - Melhorar descrição

---

swagger-apis/payments/3.0.0.yml
swagger-apis/payments/index.html

Reverts Sensedia/draft-openapi#2428

Revert "Revert "feat(Payments): ORB-3638 - alterar versão""

---

dictionary/getBankingAgents_v2.csv
dictionary/getBranches_v2.csv
dictionary/getElectronicChannels_v2.csv
dictionary/getPhoneChannels_v2.csv
dictionary/getSharedAutomatedTellerMachines_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml

feat(Channels): ORB-3632 - PDA183 - Patterns - Ajustes

---

swagger-apis/consents/3.0.0-beta.1.yml

feat(Consents): ORB-3657 - PDC166 - Alterar propriedade do campo x-fapi-interaction-id

---

dictionary/resourcesGetResources_v3.csv
swagger-apis/resources/3.0.0-beta.1.yml
swagger-apis/resources/index.html

feat(Resources): ORB-3666 - PDC177 - Complementar texto no header da API

---

dictionary/resourcesGetResources_v3.csv
swagger-apis/resources/3.0.0-beta.1.yml
swagger-apis/resources/index.html

feat(Resources): ORB-3665 - PDC191 - Alterar propriedade do campo x-fapi-interaction-id

---

swagger-apis/exchanges/1.0.0-rc2.0.yml
swagger-apis/exchanges/index.html

feat(Exchanges): ORB-3646 - SPA62 - Ajustar propriedades de campo pageSize

---

swagger-apis/channels/2.0.0-beta.1.yml

feat(Channels): ORB-3609 - PDA166 - Status code - criar

---

swagger-apis/funds/1.0.2.yml
swagger-apis/funds/index.html

feat(Funds): ORB-3703 - PDC210 - Alterar a descrição do endpoint balances

---

swagger-apis/payments/4.0.0-beta.1.yml

Feat(payments) adicionando correções na versão 4

---

swagger-apis/consents/2.2.0-beta.2.yml
swagger-apis/consents/index.html

feat(Consents): ORB-3749 - PRS13 - Corrigir definições de erro 422 endpoints post_consents_extends

---

dictionary/paymentsGetConsentsConsentId_v4.csv
dictionary/paymentsPostConsents_v4.csv
swagger-apis/payments/4.0.0-beta.1.yml

feat(Payments): ORB-3762 - PSV95 - Ajustar descrição header da API

---

dictionary/paymentsGetConsentsConsentId_v4.csv
dictionary/paymentsPostConsents_v4.csv
swagger-apis/payments/4.0.0-beta.1.yml

feat(Payments): ORB-3763 - PSV102 - Ajustar descrição header da API

---

dictionary/paymentsGetConsentsConsentId_v4.csv
dictionary/paymentsPostConsents_v4.csv
swagger-apis/payments/4.0.0-beta.1.yml

feat(Payments): ORB-3764 - PSV103 - Atualizar definição de controle de acesso da API

---

swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-3776 - Criar endpoint PATCH de Pagamentos recorrente

---

dictionary/financingsGetContractsContractId_v2.csv
swagger-apis/financings/2.1.0-rc.2.yml
swagger-apis/financings/index.html

feat(Financings): ORB-3814 - Atualizar descrição do campo CET

---

dictionary/invoiceFinancingsGetContractsContractId_v2.csv
swagger-apis/invoice-financings/2.1.0-rc.2.yml
swagger-apis/invoice-financings/index.html

feat(Invoice Financings): ORB-3822 - Atualizar descrição do campo CET

---

dictionary/loansGetContractsContractId_v2.csv
swagger-apis/loans/2.1.0-rc.2.yml

feat(Loans): ORB-3803 - PDC224 - Atualizar texto do header da API

---

dictionary/getBusinessCreditCards_v1.csv
dictionary/getPersonalCreditCards_v1.csv
swagger-apis/opendata-creditcards/1.0.0-beta.2.yml

feat(Opendata Credit Cards): ORB-3832 - PDA191 - Services - Melhorar descrição

---

automation-scripts/dictionary_generator
dictionary/getBusinessFinancings_v1.csv
dictionary/getPersonalFinancings_v1.csv
swagger-apis/opendata-financings/1.0.0-beta.2.yml

feat(Opendata Financings): ORB-3850 - PDA200 - minItems array

---

automation-scripts/dictionary_generator
dictionary/getBusinessInvoiceFinancings_v1.csv
dictionary/getPersonalInvoiceFinancings_v1.csv
swagger-apis/opendata-invoicefinancings/1.0.0-beta.2.yml

feat(Opendata Invoice Financings): ORB-3851 - PDA200 - minItems array

---

automation-scripts/dictionary_generator
dictionary/getBusinessUnarrangedAccountOverdraft_v1.csv
dictionary/getPersonalUnarrangedAccountOverdraft_v1.csv
swagger-apis/opendata-unarranged/1.0.0-beta.2.yml

feat(Opendata Unarranged): ORB-3852 - PDA200 - minItems array

---

automation-scripts/dictionary_generator
dictionary/paymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/paymentsGetPixRecurringPayments_v1.csv
dictionary/paymentsGetRecurringConsentsConsentId_v1.csv
dictionary/paymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/paymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/paymentsPostPixRecurringPayments_v1.csv
dictionary/paymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-3784 - PSV94 - Adicionar motivo de rejeição nos endpoints de pagamento da API

---

automation-scripts/dictionary_generator
dictionary/paymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/paymentsGetPixRecurringPayments_v1.csv
dictionary/paymentsGetRecurringConsentsConsentId_v1.csv
dictionary/paymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/paymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/paymentsPostPixRecurringPayments_v1.csv
dictionary/paymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-3908 - PSV107 - Adicionar campo ibgeTownCode

---

swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-3909 - PSV105 - Definir parâmetros de motivos de rejeição e revogação sync e async

---

dictionary/unarrangedAccountsOverdraftGetContractsContractIdWarranties_v2.csv
swagger-apis/unarranged-accounts-overdraft/2.1.0-rc.2.yml
swagger-apis/unarranged-accounts-overdraft/index.html

feat(Unarranged Accounts Overdraft): ORB-3940 - PDC234 - Adicionar restrição ao campo warrantyAmount

---

dictionary/financingsGetContractsContractIdWarranties_v2.csv
swagger-apis/financings/2.1.0-rc.2.yml

feat(Financings): ORB-3941 - PDC234 - Adicionar restrição ao campo warrantyAmount

---

swagger-apis/payments/4.0.0-beta.1.yml

feat(Payments): ORB-3953 - PSV116 - Header Swagger - Inserir

---

swagger-apis/payments/4.0.0-beta.1.yml

feat(Payments): ORB-3954 - PSV116 - status code - 422 - Adicionar opção de enum

---

swagger-apis/payments/4.0.0-beta.1.yml

feat(Payments): ORB-3955 - PSV116 - 422 - Consentimento inválido - Alterar descrição

---

dictionary/paymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/paymentsGetPixRecurringPayments_v1.csv
dictionary/paymentsGetRecurringConsentsConsentId_v1.csv
dictionary/paymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/paymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/paymentsPostPixRecurringPayments_v1.csv
dictionary/paymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.1.yml

fix(Automatic Payments): fix requestBody get consentId

---

dictionary/paymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/paymentsGetPixRecurringPayments_v1.csv
dictionary/paymentsGetRecurringConsentsConsentId_v1.csv
dictionary/paymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/paymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/paymentsPostPixRecurringPayments_v1.csv
dictionary/paymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.1.yml

fix(Automatic Payments): fix requestBody get paymenttId

---

swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-3998 - PSV128 - Campos - Editar payload

---

swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-4000 - PSV130 - Header da API - Adicionar texto

---

swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-4016 - PSV122 -  Criar novo Security Schema

---

swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-4024 - PSV123 - Criar as respostas de erro do endpoint GET

---

swagger-apis/webhook/1.2.0.yml
swagger-apis/webhook/index.html

feat(Webhook): ORB-4026 - SB56- Ajustar Tags de Webhook

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-4028 - PSV133 - Adicionar um rejectionReason

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-4029 - PSV133 - Adicionar texto header API

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-4001 - PSV131 - Adição do campo proxy

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-4002 - PSV131 - Adição do campo localInstrument

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-4003 - PSV131 - Adição de restrição

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-4006 - PSV131 - localInstrument - Adição do INIC

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.1.yml

feat(Automatic Payments): ORB-4030 - SB57 - Ajustar conteúdo do header da API de Pagamentos Automáticos

---

dictionary/paymentsGetPixPaymentsPaymentId_v4.csv
swagger-apis/payments/4.0.0-beta.2.yml
swagger-apis/payments/index.html

feat(Payments): ORB-4048 - SB62 - Ajustar retorno do endpoint GET_pix_payments_paymentId

---

swagger-apis/consents/2.2.0.yml

Fix example consents

---

dictionary/loansGetContractsContractIdWarranties_v2.csv
swagger-apis/loans/2.1.0.yml
swagger-apis/loans/index.html

feat(Loans): ORB-4067 - PDC234 - alterar a restrição do campo warrantyAmount

---

dictionary/financingsGetContractsContractIdWarranties_v2.csv
swagger-apis/financings/2.1.0.yml
swagger-apis/financings/index.html

feat(Financings): ORB-4074 - PDC234 - alterar a restrição do campo warrantyAmount

---

dictionary/unarrangedAccountsOverdraftGetContractsContractIdWarranties_v2.csv
swagger-apis/unarranged-accounts-overdraft/2.1.0.yml

feat(Unarranged Accounts Overdraft): ORB-4088 -  PDC234 - Alterar a restrição do campo warrantyAmount

---

swagger-apis/automatic-payments/1.0.0-beta.2.yml
swagger-apis/automatic-payments/index.html

feat(Automatic Payments): ORB-4108 - PSV135 - Ajustar descrição do header da AP

---

dictionary/enrollmentCreateFidoRegistrationOptions_v1.csv
dictionary/enrollmentCreateFidoSigningOptions_v1.csv
swagger-apis/enrollments/1.2.0.yml
swagger-apis/enrollments/index.html

feat(Enrollments): ORB-4117 - PJR31 - Alterar e adicionar campos

---

dictionary/enrollmentCreateFidoRegistrationOptions_v1.csv
dictionary/enrollmentCreateFidoSigningOptions_v1.csv
swagger-apis/enrollments/1.2.0.yml
swagger-apis/enrollments/index.html

feat(Enrollments): ORB-4119 - PJR32 - Alterar a descrição do campo platform

---

dictionary/enrollmentCreateFidoRegistrationOptions_v1.csv
swagger-apis/enrollments/1.2.0.yml

feat(Enrollments): ORB-4138 - PJR31 - Alterar descrição do campo

---

dictionary/consentsGetConsentsConsentIdExtends_v3.csv
dictionary/consentsPostConsentsConsentIdExtends_v3.csv
swagger-apis/consents/3.0.0-beta.1.yml

feat(Consents): ORB-4132 - PDC229 - Alterar propriedades do campo expirationDateTime

---

dictionary/consentsGetConsentsConsentIdExtends_v3.csv
dictionary/consentsPostConsentsConsentIdExtends_v3.csv
swagger-apis/consents/3.0.0-beta.1.yml

feat(Consents): ORB-4145 - PDC236 - Remover código de erro REFRESH_TOKEN_JWT

---

dictionary/consentsGetConsentsConsentIdExtends_v3.csv
dictionary/consentsPostConsentsConsentIdExtends_v3.csv
swagger-apis/consents/3.0.0-beta.1.yml

feat(Consents): ORB-4148 - PDC239 - Incluir campos no endpoint _extends da API

---

dictionary/consentsGetConsentsConsentIdExtends_v3.csv
dictionary/consentsPostConsentsConsentIdExtends_v3.csv
swagger-apis/consents/3.0.0-beta.1.yml

feat(Consents): ORB-4149 - PDC242 - remover campos totalPages e totalRecords

---

dictionary/getBranches_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml

feat(Channels): ORB-4158 - PDA203 -  Ajustar nomenclatura de objeto no endpoint _branches da API

---

dictionary/getBankingAgents_v2.csv
dictionary/getBranches_v2.csv
dictionary/getElectronicChannels_v2.csv
dictionary/getPhoneChannels_v2.csv
dictionary/getSharedAutomatedTellerMachines_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml

feat(Channels): ORB-4159 - PDA204- Alterar patterns dos endpoints da API de Canais de Atendimentos

---

dictionary/getBankingAgents_v2.csv
dictionary/getPhoneChannels_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml

feat(Channels): ORB-4165 - PDA215 -  Ajustar propriedade do campo number

---

dictionary/getBankingAgents_v2.csv
dictionary/getPhoneChannels_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml

feat(Channels): ORB-4166 - PDA216 - Atualizar minItems em campos do tipo array

---

swagger-apis/automatic-payments/1.0.0-beta.2.yml

feat(Automatic Payments): ORB-4195 - SB68 - Ajustar descrição do campo detail http 422 da API

---

swagger-apis/payments/4.0.0-beta.3.yml
swagger-apis/payments/index.html

feat(Payments): ORB-4261 - PSV144 - Incluir texto no Header da API

---

dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.3.yml

feat(Automatic Payments): ORB-4256 - PSV143 - remover o campo data_debtorAccount_overdraftLimit

---

dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.3.yml

feat(Automatic Payments): ORB-4257 - PSV145 - Atualizar o summary do endpoint PATCH de pagamentos

---

dictionary/getBankingAgents_v2.csv
dictionary/getBranches_v2.csv
dictionary/getElectronicChannels_v2.csv
dictionary/getPhoneChannels_v2.csv
dictionary/getSharedAutomatedTellerMachines_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml

fix(Channels): ORB-4267 - PDA217 - urlComplementarList - Ajuste texto

---

dictionary/getBankingAgents_v2.csv
dictionary/getBranches_v2.csv
dictionary/getElectronicChannels_v2.csv
dictionary/getPhoneChannels_v2.csv
dictionary/getSharedAutomatedTellerMachines_v2.csv
swagger-apis/channels/2.0.0-beta.1.yml

fix(Channels): ORB-4269 - PDA221 - additionalInfo - Ajustar o exemplo

---

swagger-apis/accounts/2.1.1.yml
swagger-apis/accounts/index.html

feat(Accounts): ORB-4339 - PDC252 - Adicionar texto no Header da API

---

dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.4.yml
swagger-apis/automatic-payments/index.html

feat(Automatic Payments): ORB-4356 - PSV155 - Ajustar descrição de campo

---

swagger-apis/exchanges/1.0.0-rc.3.yml
swagger-apis/exchanges/index.html

feat(Exchanges): ORB-4376 - PDC255 - Remover campos firs_prev_next_last de endpoints

---

dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.csv
dictionary/accountsGetAccountsAccountIdTransactions_v2.csv
swagger-apis/accounts/2.2.0.yml
swagger-apis/accounts/index.html

feat(Accounts): ORB-4391 - PA124 - Alterar campos transactionDate

---

automation-scripts/dictionary_generator
dictionary/getOutage_v2.csv
swagger-apis/common/2.0.0-beta.2.yml
swagger-apis/common/index.html

feat(Common): ORB-4345 - SC10 - Dicionário de dados - Ajustes

---

swagger-apis/payments/4.0.0-beta.4.yml
swagger-apis/payments/index.html

feat(Payments): ORB-4404 - PSV158 - Ajustar descrição do campo x-fapi-interaction-Id na API

---

swagger-apis/automatic-payments/1.0.0-beta.5.yml
swagger-apis/automatic-payments/index.html

feat(Automatic Payments): ORB-4411 - PSV158 - Ajustar descrição do campo x-fapi-interaction-Id na API

---

dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.5.yml

Feat(Automatic Payments): ORB-4419 - PSV163 - Alterar a restrição do objeto riskSignals na API

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.5.yml

feat(Automatic Payments): ORB-4426 - PSV167 - Alterar a mandatoriedade do campo data_businessEntity na API

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.5.yml

feat(Automatic Payments): ORB-4427 - PSV169 - Alterar propriedades do campo pixKeyRegistrationDateTime na API

---

dictionary/getOutage_v2.csv
dictionary/getStatus_v2.csv
swagger-apis/common/2.0.0-beta.2.yml

feat(Common): ORB-4433 - PDA234 - Ajuste pattern de campos string​

---

dictionary/getStatus_v2.csv
swagger-apis/common/2.0.0-beta.2.yml

fix(Comuns): ORB-4443 - PDA229 - Remover aspas do final

---

dictionary/variableIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.csv
dictionary/variableIncomesGetInvestmentsInvestmentIdTransactions_v1.csv
swagger-apis/variable-incomes/1.1.0.yml
swagger-apis/variable-incomes/index.html

feat(Variable Incomes): ORB-4449 - PDC263 - Alterar a restrição do campo transactionQuantity

---

swagger-apis/resources/3.0.0-beta.2.yml
swagger-apis/resources/index.html

feat(Resources): ORB-4463 - SA31 - Adcionar campos totalPages e totalReords

---

swagger-apis/exchanges/1.0.0-rc.4.yml
swagger-apis/exchanges/index.html

feat(Exchanges): ORB-4507 - PDC268 - Alterar propriedades do campo x-fapi-interaction-id

---

swagger-apis/payments/4.0.0-beta.5.yml
swagger-apis/payments/index.html

Feat(Payments): ORB-4516 - PSV172 - Ajustar descrição do campo x-fapi-interaction-Id na API

---

swagger-apis/payments/4.0.0-beta.5.yml
swagger-apis/payments/index.html

Feat(Payments): ORB-4517 - PSV171 -  Atualizar texto no header da API

---

swagger-apis/payments/4.0.0-beta.5.yml
swagger-apis/payments/index.html

Feat(Payments): ORB-4518 - PSV173 - Alterar propriedades do campo x-fapi-interaction-id

---

swagger-apis/automatic-payments/1.0.0-beta.6.yml
swagger-apis/automatic-payments/index.html

feat(Automatic Payments): ORB-4525 - PSV172 - Ajustar descrição do campo x-fapi-interaction-Id

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
swagger-apis/automatic-payments/1.0.0-beta.6.yml

feat(Automatic Payments): ORB-4537 - PSV177 - Adicionar restrição no  campo transactionIdentification

---

dictionary/getBankingAgents_v2.csv
dictionary/getBranches_v2.csv
dictionary/getSharedAutomatedTellerMachines_v2.csv
swagger-apis/channels/2.0.0-rc.1.yml
swagger-apis/channels/index.html

Feat(Channels): ORB-4546 - PDA241 - Corrigir pattern em campos do tipo TimeString

---

swagger-apis/automatic-payments/1.0.0-rc.1.yml

Fix(Automatic Payments): ORB-4560 - PSV177 - Ajustar restrição no campo transactionIdentification

---

dictionary/enrollmentCreateFidoRegistrationOptions_v1.csv
dictionary/enrollmentCreateFidoSigningOptions_v1.csv
dictionary/getEnrollment_v1.csv
swagger-apis/enrollments/1.3.0.yml
swagger-apis/enrollments/index.html

feat(Enrollments): ORB-4575 - PJR34 - Remover campos transports

---

dictionary/enrollmentCreateFidoRegistrationOptions_v1.csv
dictionary/enrollmentCreateFidoSigningOptions_v1.csv
dictionary/getEnrollment_v1.csv
swagger-apis/enrollments/1.3.0.yml
swagger-apis/enrollments/index.html

feat(Enrollments): ORB-4576 - PJR35 - Alterar a descrição do campo x-fapi-interaction-id 

---

dictionary/enrollmentCreateFidoRegistrationOptions_v1.csv
dictionary/enrollmentCreateFidoSigningOptions_v1.csv
dictionary/getEnrollment_v1.csv
swagger-apis/enrollments/1.3.0.yml
swagger-apis/enrollments/index.html

feat(Enrollments): ORB-4577 - PJR36 - Alterar propriedades do campo x-fapi-interaction-id

---

dictionary/enrollmentCreateFidoRegistrationOptions_v1.csv
dictionary/enrollmentCreateFidoSigningOptions_v1.csv
dictionary/getEnrollment_v1.csv
swagger-apis/enrollments/1.3.0.yml
swagger-apis/enrollments/index.html

feat(Enrollments): ORB-4578 - PJR37 - Remover o http response error 429 da API

---

swagger-apis/consents/3.0.0-rc.1.yml
swagger-apis/consents/index.html

feat(Consents): ORB-4586 - SA36 - Incluir totalPages e totalRecords

---

dictionary/capitalizationBondsGetProducts_v2.csv
swagger-apis/capitalization-bonds/2.0.0-beta.1.yml

Feat(Capitalization Bonds): ORB-4613 - PDA237 - Reestruturação da API

---

dictionary/capitalizationBondsGetProducts_v2.csv
swagger-apis/capitalization-bonds/2.0.0-beta.1.yml

Feat(Capitalization Bonds): ORB-4612 - PDA239 - Remoção do uso de NAs e suas variantes

---

dictionary/capitalizationBondsGetProducts_v2.csv
swagger-apis/capitalization-bonds/2.0.0-beta.1.yml

Feat(Capitalization Bonds): ORB-4620 - PDA242 - Redefinir as propriedades dos campos minimum e maximum

---

swagger-apis/enrollments/1.3.0.yml

Feat(Enrollments): ORB-4642 - PJR43 -Alterar descrições de campos do endpoint fido_registration

---

dictionary/getBankingAgents_v2.csv
swagger-apis/channels/2.0.0-rc.2.yml
swagger-apis/channels/index.html

Feat(Channels): ORB-4646 - PDA257 - Alterar as características do campo data

---

dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-rc.2.yml

Feat(Automatic Payments): ORB-4643 - PSV181 - Alterar restrição de campos

---

dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.0.0-rc.2.yml

Feat(Automatic Payments): ORB-4644 - PSV182 - Alterar descrição do schema de segurança OAuth2ClientCredentials

---

swagger-apis/payments/4.0.0.yml
swagger-apis/payments/index.html

Feat(Payments): ORB-4655 - PSV182 - Alterar descrição do schema de segurança OAuth2ClientCredentials

---

dictionary/getBusinessLoans_v1.csv
dictionary/getPersonalLoans_v1.csv
swagger-apis/opendata-loans/1.0.0-rc.2.yml
swagger-apis/opendata-loans/index.html

feat(OpenData Loans): ORB-4669 - PDA256 - Alterar descrição do campo /data[]/intrestRates/rate

---

dictionary/getBusinessFinancings_v1.csv
dictionary/getPersonalFinancings_v1.csv
swagger-apis/opendata-financings/1.0.0-rc.2.yml
swagger-apis/opendata-financings/index.html

feat(OpenData Financings): ORB-4672 - PDA256 - Alterar descrição e exemplo do campo /data[]/intrestRates/aplications/indexer/rate

---

dictionary/getBusinessLoans_v1.csv
dictionary/getPersonalLoans_v1.csv
swagger-apis/opendata-loans/1.0.0-rc.2.yml

feat(OpenData Loans): ORB-4668 - PDA256 - Alterar descrição e exemplo do campo /data[]/intrestRates/aplications/indexer/rate

---

dictionary/getBusinessInvoiceFinancings_v1.csv
dictionary/getPersonalInvoiceFinancings_v1.csv
swagger-apis/opendata-invoicefinancings/1.0.0-rc.2.yml
swagger-apis/opendata-invoicefinancings/index.html

feat(OpenData Invoice Financings): ORB-4675 - PDA256 - Alterar descrição do campo /data[]/intrestRates/rate

---

dictionary/getBusinessFinancings_v1.csv
dictionary/getPersonalFinancings_v1.csv
swagger-apis/opendata-financings/1.0.0-rc.2.yml
swagger-apis/opendata-financings/index.html

feat(OpenData Financings): ORB-4671 - PDA256 - Alterar descrição do campo /data[]/intrestRates/rate

---

dictionary/getBusinessUnarrangedAccountOverdraft_v1.csv
dictionary/getPersonalUnarrangedAccountOverdraft_v1.csv
swagger-apis/opendata-unarranged/1.0.0-rc.2.yml
swagger-apis/opendata-unarranged/index.html

feat(OpenData Unarranged): ORB-4678 - PDA256 - Alterar descrição do campo /data[]/intrestRates/rate

---

dictionary/capitalizationBondsGetProducts_v2.csv
swagger-apis/capitalization-bonds/2.0.0-beta.1.yml

Feat(Capitalization Period): ORB-4640 - PDA244 - Ajustar descrições de campos

---

swagger-apis/channels/2.0.0.yml
swagger-apis/channels/index.html

GT Dados Abertos | Canais de atendimento / OpenData Channels | Versão 2.0.0

---

dictionary/getPensionRiskCoverages_v2.csv
dictionary/getPensionSurvivalCoverages_v2.csv
swagger-apis/pension/2.0.0-beta.1.yml

feat(Pension): ORB-4720 - PDA259 - Alterar opção de ENUM do campo contributionPaymentMethod

---

dictionary/paymentsGetConsentsConsentId_v4.csv
dictionary/paymentsPostConsents_v4.csv
swagger-apis/payments/4.0.0-rc.2.yml

feat(Payments): ORB-4726 - PSV190 - Ajustar o campo expirationDateTime na etapa do consentimento

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.csv
swagger-apis/credit-cards/2.2.1.yml
swagger-apis/credit-cards/index.html

Feat(Credit Card): ORB-4731 - PDC287 - Alterar descrição de endpoints da API Cartão de Crédito

---

dictionary/getPensionRiskCoverages_v2.csv
dictionary/getPensionSurvivalCoverages_v2.csv
swagger-apis/pension/2.0.0-beta.1.yml

feat(Pension): ORB-4734 - PDA264 - Incluir exemplos em campos

---

dictionary/getPensionRiskCoverages_v2.csv
dictionary/getPensionSurvivalCoverages_v2.csv
swagger-apis/pension/2.0.0-beta.1.yml

feat(Pension): ORB-4735 - PDA265 - Ajustar de nomenclatura em campo

---

dictionary/exchangesGetOperationsOperationIdEvents_v1.csv
dictionary/exchangesGetOperationsOperationId_v1.csv
swagger-apis/exchanges/1.0.0-rc.6.yml
swagger-apis/exchanges/index.html

feat(Exchanges): EOF-48 - PDC289 - Proposta para ajustar o campo deliveryForeignCurrency API de Câmbio

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
swagger-apis/automatic-payments/1.0.0-rc.4.yml

fix(Automatic Payments): Reverter alteração em descrição do campo riskSignals/manual

---

dictionary/getPersonalInsurance_v2.csv
swagger-apis/insurances/2.0.0-beta.1.yml
swagger-apis/insurances/index.html

feat(Insurances): EOF-53 - PDA269 - Proposta para definir/ajustar pattern em campos de texto livre da API Seguros

---

dictionary/getPersonalInsurance_v2.csv
swagger-apis/insurances/2.0.0-beta.1.yml

feat(Insurances): EOF-82 - PDA277 - Ajustar opções de ENUMs

---

dictionary/getPersonalInsurance_v2.csv
swagger-apis/insurances/2.0.0-beta.1.yml

feat(Insurances): EOF-83 - PDA278- Criar campo paymentMethodAdittionalInfo

---

dictionary/getPersonalInsurance_v2.csv
swagger-apis/insurances/2.0.0-beta.1.yml

feat(Insurance): EOF-92 - PDA281 - Incluir exemplos na API Seguros

---

dictionary/getPersonalInsurance_v2.csv
swagger-apis/insurances/2.0.0-beta.1.yml

feat(insurances): EOF-123 - PDA281 - Alterar pattern de campos

---

dictionary/getPersonalInsurance_v2.csv
swagger-apis/insurances/2.0.0-beta.1.yml

feat(insurances): EOF-124 - PDA283 - Alterar nomenclatura

---

dictionary/getPersonalInsurance_v2.csv
swagger-apis/insurances/2.0.0-beta.2.yml

feat(Insurances): EOF-147 - PDA291 - Remover NAs

---

dictionary/customersGetBusinessFinancialRelations_v2.csv
dictionary/customersGetBusinessIdentifications_v2.csv
dictionary/customersGetBusinessQualifications_v2.csv
dictionary/customersGetPersonalFinancialRelations_v2.csv
dictionary/customersGetPersonalIdentifications_v2.csv
dictionary/customersGetPersonalQualifications_v2.csv
swagger-apis/customers/2.2.0.yml
swagger-apis/customers/index.html

feat(Customers): EOF-162 - PDC309 - Incluir os dados do empregador na API Dados cadastrais

---

swagger-apis/loans/2.2.0.yml
swagger-apis/loans/index.html

feat(Loans): EOF-169 - SA61 - Alterar a obrigatoriedade e descrição do parâmetro x-fapi-interaction-id na API

---

swagger-apis/loans/2.2.0.yml
swagger-apis/loans/index.html

feat(Loans): EOF-170 - SA60 - Ajustes do tamanho máximo de campos

---

dictionary/loansGetContractsContractId_v2.csv
swagger-apis/loans/2.2.0.yml
swagger-apis/loans/index.html

feat(Loans): EOF-171 - SA59 - Ajustes do campo contractNumber

---

dictionary/loansGetContractsContractId_v2.csv
dictionary/loansGetContracts_v2.csv
swagger-apis/loans/2.2.0.yml
swagger-apis/loans/index.html

feat(Loans): EOF-172 - SA58 - Solicitação para ajustes do campo ipocCode​

---

dictionary/loansGetContractsContractId_v2.csv
swagger-apis/loans/2.2.0.yml

feat(Loans): EOF-173 - SA57 -Ajustes de campos na API - Operações de Crédito - Empréstimos

---

dictionary/accountsGetAccountsAccountIdBalances_v2.csv
dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.csv
dictionary/accountsGetAccountsAccountIdTransactions_v2.csv
swagger-apis/accounts/2.3.0.yml
swagger-apis/accounts/2.4.0.yml
swagger-apis/accounts/index.html

feat(Accounts): EOF-174 - SA56 - Ajustes do campo /automaticallyInvestedAmount/amount​

---

dictionary/customersGetBusinessIdentifications_v2.csv
swagger-apis/customers/2.1.0-beta.2.yml
swagger-apis/customers/index.html

feat(Customers): EOF-192 - SA67 - Ajuste do parâmetro x-fapi-interaction-id 

---

dictionary/customersGetBusinessIdentifications_v2.csv
swagger-apis/customers/2.1.0-beta.2.yml
swagger-apis/customers/index.html

feat(Customers): EOF-194 - SA65- Ajustes dos campos address e townName da API Dados Cadastrais

---

dictionary/customersGetBusinessIdentifications_v2.csv
swagger-apis/customers/2.1.0-beta.2.yml
swagger-apis/customers/index.html

feat(Customers): EOF-195 - SA64 - Ajustes do campo postalAddresses da API Dados Cadastrais

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v1.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
dictionary/automaticPaymentsPostRecurringConsents_v1.csv
swagger-apis/automatic-payments/1.1.0.yml
swagger-apis/automatic-payments/index.html

feat(Automatic Payments): EOF-229 - PSV210 - Alterar o valor no domínio do ENUM /data/status

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
swagger-apis/automatic-payments/1.1.0.yml

feat(Automatic Payments): EOF-238 - PSV215 - Ajustar a descrição do campo

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
swagger-apis/automatic-payments/1.1.0.yml

feat(Automatic Payments): EOF-239 - PSV213 - Ajustar descrição do campo

---

swagger-apis/automatic-payments/1.1.0.yml

feat(Automatic Payments): EOF-247 - PSV216 - Adicionar um novo código ao enum dos erros 422

---

dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
swagger-apis/automatic-payments/1.1.0.yml

feat(Automatic Payments): EOF-248 - PSV216 - Adicionar um novo rejectionreason na resposta do endpoint

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
swagger-apis/automatic-payments/1.1.0.yml

feat(Automatic Payments): EOF-249 - PSV216 - Adicionar um novo rejectionreason na resposta do endpoint

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
swagger-apis/automatic-payments/1.1.0.yml

feat(Automatic Payments): EOF-250 - PSV216 - Adicionar um novo rejectionreason na resposta do endpoint

---

dictionary/customersGetPersonalFinancialRelations_v2.csv
swagger-apis/customers/2.1.0-beta.3.yml
swagger-apis/customers/index.html

feat(Customers): EOF-254 - PDC335 - Ajustar as descrições dos campos

---

dictionary/financingsGetContractsContractId_v2.csv
dictionary/financingsGetContracts_v2.csv
swagger-apis/financings/2.2.0.yml

feat(Financings): EOF-266 - SA95 - Solicitação para ajustes de campos

---

dictionary/financingsGetContractsContractId_v2.csv
dictionary/financingsGetContracts_v2.csv
swagger-apis/financings/2.2.0.yml

feat(Financings):EOF-269 - SA98 - Solicitação para ajustes do tamanho máximo de campos

---

dictionary/financingsGetContractsContractId_v2.csv
dictionary/financingsGetContracts_v2.csv
swagger-apis/financings/2.2.0.yml

feat(Financings): EOF-277 - SA106 - Solicitação para ajuste da API

---

dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.csv
dictionary/unarrangedAccountsOverdraftGetContracts_v2.csv
swagger-apis/unarranged-accounts-overdraft/2.2.0.yml

feat(Unarranged): EOF-264 - SA93 - Solicitação para ajustes de campos

---

dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.csv
dictionary/unarrangedAccountsOverdraftGetContracts_v2.csv
swagger-apis/unarranged-accounts-overdraft/2.2.0.yml

feat(Unarranged): EOF-267 - SA96 - Solicitação para ajustes do tamanho máximo

---

dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.csv
dictionary/unarrangedAccountsOverdraftGetContracts_v2.csv
swagger-apis/unarranged-accounts-overdraft/2.2.0.yml

feat(Unarranged): EOF-272 - SA101 -Solicitação para ajustes de campos

---

dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.csv
dictionary/unarrangedAccountsOverdraftGetContracts_v2.csv
swagger-apis/unarranged-accounts-overdraft/2.2.0.yml

feat(Unarranged): EOF-273 - SA102 -Solicitação para ajustes de campos

---

dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.csv
dictionary/unarrangedAccountsOverdraftGetContracts_v2.csv
swagger-apis/unarranged-accounts-overdraft/2.2.0.yml

feat(Unarranged): EOF-275 - SA104 - Solicitação para ajuste da API

---

dictionary/invoiceFinancingsGetContractsContractIdPayments_v2.csv
dictionary/invoiceFinancingsGetContractsContractIdScheduledInstalments_v2.csv
dictionary/invoiceFinancingsGetContractsContractId_v2.csv
dictionary/invoiceFinancingsGetContracts_v2.csv
swagger-apis/invoice-financings/2.2.0.yml

feat(Invoice): EOF-265 - SA94 - Solicitação para ajustes de campos

---

dictionary/invoiceFinancingsGetContractsContractIdPayments_v2.csv
dictionary/invoiceFinancingsGetContractsContractIdScheduledInstalments_v2.csv
dictionary/invoiceFinancingsGetContractsContractId_v2.csv
dictionary/invoiceFinancingsGetContracts_v2.csv
swagger-apis/invoice-financings/2.2.0.yml

feat(Invoice): EOF-268 - SA97 - Solicitação para ajustes do tamanho

---

dictionary/invoiceFinancingsGetContractsContractIdPayments_v2.csv
dictionary/invoiceFinancingsGetContractsContractIdScheduledInstalments_v2.csv
dictionary/invoiceFinancingsGetContractsContractId_v2.csv
dictionary/invoiceFinancingsGetContracts_v2.csv
swagger-apis/invoice-financings/2.2.0.yml

feat(Invoice): EOF-274 - SA103 - Solicitação para ajustes de campos

---

dictionary/invoiceFinancingsGetContractsContractIdPayments_v2.csv
dictionary/invoiceFinancingsGetContractsContractIdScheduledInstalments_v2.csv
dictionary/invoiceFinancingsGetContractsContractId_v2.csv
dictionary/invoiceFinancingsGetContracts_v2.csv
swagger-apis/invoice-financings/2.2.0.yml

feat(Invoice): EOF-276 - SA105 - Solicitação para ajuste da API

---

dictionary/invoiceFinancingsGetContractsContractIdPayments_v2.csv
dictionary/invoiceFinancingsGetContractsContractIdScheduledInstalments_v2.csv
dictionary/invoiceFinancingsGetContractsContractId_v2.csv
dictionary/invoiceFinancingsGetContracts_v2.csv
swagger-apis/invoice-financings/2.2.0.yml

feat(Invoice): EOF-279 - SA108 - Solicitação para ajuste de descrição

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
swagger-apis/automatic-payments/1.1.0.yml

feat(automatic payments): EOF-292 - PSV227 - Proposta para ajuste

---

swagger-apis/automatic-payments/1.1.0.yml

feat(Automatic Payments): EOF-294 - PSV230 - Proposta para ajustar

---

swagger-apis/enrollments/1.4.0.yml

feat(Enrollments): EOF-296 - PJR49 - Proposta para alterar campos que representam links

---

swagger-apis/enrollments/1.4.0.yml

feat(Enrollments): EOF-297 - PJR50 - Proposta para retirar a restrição do campo screenBrightness

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
swagger-apis/automatic-payments/1.1.0.yml

feat(Automatic Payments): EOF-312 - PSV230 - Corrigir divergência encontrada durante o processo de homologação

---

index.html

feat(batch payments): EOF-310 - PSV228 - Proposta de definição dos pa…

Fix-batch-payments

---

swagger-apis/batch-payments/1.0.0-beta.1.yml

fix(Batch Payments): EOF-328 - PSV228 - GET /consents/{consentId}: Para consultar consentimentos

---

swagger-apis/batch-payments/1.0.0-beta.1.yml

fix(Batch Payments): EOF-332 - PSV228 - PATCH /consents/{consentId}/draft-payments

---

swagger-apis/batch-payments/1.0.0-beta.1.yml

fix(batch payments): EOF-335 - PSV228 - GET /consents/{consentId}/payments

---

swagger-apis/batch-payments/1.0.0-beta.1.yml

fix(batch paymentes): EOF-336 - PSV228 -POST /consents/{consentId

---

swagger-apis/batch-payments/1.0.0-beta.1.yml

Fix(batch Payments): EOF-338 - PSV238 - Motivos de rejeição assíncronos

---

swagger-apis/batch-payments/1.0.0-beta.1.yml

Fix(batch payments): EOF-342 - PSV238 - Motivos de rejeição síncronos

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v1.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v1.csv
swagger-apis/automatic-payments/1.1.0-rc.1.yml

Reverts Sensedia/draft-openapi#4376

Revert "feat(Automatic Payments): EOF-368 - PSV241 - Proposta para remover do…"

---

swagger-apis/enrollments/2.0.0-beta.2.yml

feat(Enrollments): EOF-374 - PJR56 - POST /enrollments/{enrollmentId}/risk-signals - Adicionar novo valor ao domínio enum no status code 422

---

swagger-apis/webhook/1.3.0-beta.1.yml
swagger-apis/webhook/index.html

feat(Webhook): EOF-378 - PDC350 - Adicionar novo endpoint

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.1.yml
swagger-apis/automatic-payments/index.html

feat(Automatic Payments): EOF-386 - PSV184 - Adição de campo

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.1.yml
swagger-apis/automatic-payments/index.html

feat(Automatic Payments): EOF-388 - PSV188 - Remover o campo ibgeTown

---

dictionary/getEnrollment_v2.csv
dictionary/postEnrollments_v2.csv
swagger-apis/enrollments/2.0.0-rc.1.yml

feat(Enrollments): EOF-392 - PJR58 - Adição de erro síncrono no endpoint de autorização de consentimento

---

dictionary/invoiceFinancingsGetContractsContractId_v2.csv
swagger-apis/invoice-financings/2.3.0.yml
swagger-apis/invoice-financings/index.html

feat(Invoice): EOF-417 - PDC363 - ajustar o pattern do campo chargeRate

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.1.yml

feat(Automatic Payments): EOF-423 - PSV185 - Ajustes nos campos amount e transactionLimit para o consentimento de Pix automático

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.1.yml

feat(Automatic Payments): EOF-424 - PSV188 - Retirar a obrigatoriedade do campo /data/ibgeTownCode da v2 de Pagamentos Automáticos

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.1.yml

feat(Automatic Payments): EOF-426 - PSV199 - adicionar o campo “authorisedAtDateTime” para consentimentos

---

swagger-apis/automatic-payments/2.0.0-beta.1.yml

feat(Automatic Payments): EOF-420 - PSV245 - Remover obrigatoriedade de campos presentes nos sinais de risco

---

swagger-apis/automatic-payments/2.0.0-beta.1.yml

feat(Automatic Payments): EOF-421 - PSV250 - Adição  de restrição ao campo creditors para consentimentos

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.1.yml

feat(Automatic Payments): EOF-428 - PSV253 - Alteração nos elementos no ENUM de periodicidade para consentimentos

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.1.yml

feat(Automatic Payments): EOF-429 - PSV252 - Ajustar os campos dayOfMonth, dayOfWeek e month para consentimentos

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.1.yml

feat(Automatic Payments): EOF-435 - PSV251 - Corrigir divergência encontrada durante o processo de homologação.

---

swagger-apis/automatic-payments/2.0.0-beta.1.yml

feat(automatic Payments): EOF-438 - PSV254 - Adição de orientação ao iniciador 

---

dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.1.yml

feat(automatic payments): EOF-440 - PSV256 - criação do campo "isRetryAccepted" 

---

dictionary/invoiceFinancingsGetContractsContractIdPayments_v2.csv
swagger-apis/invoice-financings/2.3.0.yml

feat(invoice financings): EOF-453 - PDC-373 - Ajustar o pattern

---

dictionary/loansGetContractsContractIdPayments_v2.csv
swagger-apis/loans/2.4.0.yml

feat(Loans): EOF-458 - PDC-375 - Ajustar os campos de links

---

dictionary/consentsPostConsentsConsentIdExtends_v3.csv
dictionary/consentsPostConsents_v3.csv
swagger-apis/consents/3.1.0.yml

feat(Consents): EOF-446 - PDC367 - Ajustar a descrição do campo expirationdatetime

---

dictionary/consentsPostConsentsConsentIdExtends_v3.csv
dictionary/consentsPostConsents_v3.csv
swagger-apis/consents/3.1.0.yml

feat(Consents): EOF-447 - PDC368 - Ajustar o campo code do código de erro 422

---

dictionary/financingsGetContractsContractIdPayments_v2.csv
dictionary/financingsGetContractsContractIdScheduledInstalments_v2.csv
swagger-apis/financings/2.3.0.yml

feat(Financings): EOF-452 - PDC373 - Ajustar o pattern e o maxLength do campo paidAmount

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.1.yml

feat(Automatic Payments): EOF-461 - PSV264 - Proposta para remover os campos "dayOfMonth" e "dayOfWeek"

---

dictionary/enrollmentCreateFidoRegistrationOptions_v2.csv
dictionary/getEnrollment_v2.csv
dictionary/postEnrollments_v2.csv
swagger-apis/enrollments/2.0.0.yml
swagger-apis/enrollments/index.html

feat(Enrollments): EOF-482 - PJR65 - Alterar a descrição do endpoint POST /authorise

---

dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.2.yml

feat(Automatic Payments): EOF-513 - SB108 - Ajustar hyperlink presente na descripition do endpoint PATCH /recurring-consents/{recurringConsentId}

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.2.yml

feat(Automatic Payments): EOF-519 - PSV274 - Proposta para adicionar campo com a referência do pagamento

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.2.yml

feat(Automatic Payments): EOF-520 - PSV276 - Proposta para adicionar tratamento para tentativas de pagamento fora do horário ou prazo permitido

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.2.yml

feat(Automatic Payments): EOF-526 - PSV284 - Proposta para adição de novo parâmetro de filtro no endpoint de consulta ampla de pagamentos

---

swagger-apis/automatic-payments/2.0.0-beta.2.yml

feat(Automatic Payments): EOF-533 - PSV279 - Corrigir divergência encontrada durante o processo de homologação

---

dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.2.yml

feat(automatic payments): EOF-538 - PSV289 - Proposta para ajustar campos de definição de recorrência

---

dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.csv
swagger-apis/automatic-payments/2.0.0-beta.2.yml

feat(automatic payments): EOF-539 - PSV290 - Proposta para ajustar os campos referentes

---

swagger-apis/loans/2.4.0-beta.1.yml

Feat(Loans): EOF-558, EOF-562 e PDC393a

---

swagger-apis/financings/2.4.0.yml

feat(Financings): EOF-580 - PDC400 - Proposta para padronizar o retorno de erro

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.0.0.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.0.0.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.0.0.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.0.0.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.0.0.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.0.0.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.0.0.csv
swagger-apis/automatic-payments/2.0.0-rc.1.yml

fix(automatic payments): EOF-584 - PSV304 - correções

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.0.0.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.0.0.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.0.0.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.0.0.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.0.0.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.0.0.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.0.0.csv
swagger-apis/automatic-payments/2.0.0-rc.1.yml

feat(automatic Payments): EOF-585 - PSV309 - Adicionar Erro

---

swagger-apis/automatic-payments/2.0.0-rc.1.yml

feat(automatic payments): EOF-589 - PSV314 - Adicionar orientações quanto o cancelamento de novas tentativas

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.0.0.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.0.0.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.0.0.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.0.0.csv
swagger-apis/automatic-payments/2.0.0-rc.1.yml

feat(automatic payments): EOF592 - PSV316 - Prosposta para ajustar

---

swagger-apis/automatic-payments/2.0.0-rc.1.yml

fix(Automatic Payments): EOF-598 - correção quebra de linha header da API

---

dictionary/creditPortabilityGetConcurrencyManagementContratId_v1.0.0.csv
dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

feat(Credit Portability): EOF-626 - PPC08 - Definir payload e endpoint para a Solicitação e Formalização do pedido de Portabilidade

---

dictionary/creditPortabilityGetConcurrencyManagementContratId_v1.0.0.csv
dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

feat(credit portability): EOF699 - PPC13 - Ajustar o payload do endpoint de Gestão de simultaneidade

---

dictionary/creditPortabilityGetConcurrencyManagementContratId_v1.0.0.csv
dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPostPortabilitiesPayment_v1.0.0.csv
dictionary/getAccountDataCreditPortability_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

feat(credit portability): EOF-704 - PPC17 - Definir o endpoint para comunicar a respeito da liquidação efetuada

---

dictionary/automaticPaymentsGetPixRecurringPaymentsPaymentId_v2.0.0.csv
dictionary/automaticPaymentsGetPixRecurringPayments_v2.0.0.csv
dictionary/automaticPaymentsGetRecurringConsentsConsentId_v2.0.0.csv
dictionary/automaticPaymentsPatchPixRecurringPaymentsPaymentId_v2.0.0.csv
dictionary/automaticPaymentsPatchRecurringConsentsConsentId_v2.0.0.csv
dictionary/automaticPaymentsPostPixRecurringPayments_v2.0.0.csv
dictionary/automaticPaymentsPostRecurringConsents_v2.0.0.csv
swagger-apis/automatic-payments/2.0.0.yml

feat(Automatic Payments): EOF-722 - PSV325 -Ajustar a descrição do campo que contem a data prevista de liquidação para pagamentos

---

dictionary/creditPortabilityGetConcurrencyManagementContratId_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

feat(Credit Portability): EOF-730 - PPC11 - Ajustar content para JWT

---

dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

feat(Credit Portability): EOF-756 - PPC15  - Correção na estrutura do campo "amortizationScheduledAdditionalInfo" 

---

dictionary/creditPortabilityPostPortabilitiesCancel_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

feat(Credit Portability): EOF-774 - PPC33 - Proposta para documentar

---

dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPostPortabilitiesCancel_v1.0.0.csv
dictionary/creditPortabilityPostPortabilitiesPayment_v1.0.0.csv
dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

feat(Credit portability): EOF-783 - PPC24 - Proposta para padronizar

---

dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPostPortabilitiesCancel_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

feat(credit Portability): EOF-778 - PPC29 - Proposta para ajustar o payload do endpoint de consulta da Portabilidade de Crédito

---

dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPostPortabilitiesCancel_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

feat(credit portability): EOF-777 - PPC30 - Proposta para complementar o endpoint para solicitar pedido de Portabilidade de Crédito

---

swagger-apis/credit-portability/1.0.0-beta.1.yml

fix(credit Portability): EOF-793 - PDC11 - Ajustes

---

dictionary/creditPortabilityPostPortabilitiesPayment_v1.0.0.csv
dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

fix(credit portability): EOF-789 - PDC17 - Ajustes

---

dictionary/creditPortabilityPostPortabilitiesPayment_v1.0.0.csv
dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

fix(credit portability): EOF-790 - PDC16 - Ajustes

---

dictionary/creditPortabilityGetConcurrencyManagementContratId_v1.0.0.csv
dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
dictionary/getAccountDataCreditPortability_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

feat(Credit Portability): EOF-804 - PPC21 - Ajustar nome do campo e descrição

---

dictionary/creditPortabilityGetConcurrencyManagementContratId_v1.0.0.csv
dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPostPortabilitiesCancel_v1.0.0.csv
dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
dictionary/getAccountDataCreditPortability_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

feat(Credit Portability): EOF-805 - PPC28 - Implementação realizada em outro campo

---

dictionary/creditPortabilityGetAccountData_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

fix(credit portability): EOF-810 - PPC22 - ajuste

---

dictionary/creditPortabilityGetAccountData_v1.0.0.csv
dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.1.yml

fix(credit portability): EOF-812 - PPC24 - ajustes

---

dictionary/loansGetContractsContractIdPayments_v2.5.0.csv
swagger-apis/loans/2.5.0-beta.1.yml

feat(Loans): EOF-814 - PDC-427 - Alterar o atributo maxLength dos campos Links da API Empréstimos​

---

dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPatchPortabilitiesPortabilityIdCancel_v1.0.0.csv
dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.2.yml
swagger-apis/credit-portability/index.html

feat(Credit Portability): EOF-821 - Adequar nomenclatura do dicionário de dados

---

dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPatchPortabilitiesPortabilityIdCancel_v1.0.0.csv
dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.2.yml
swagger-apis/credit-portability/index.html

feat(Credit Portability): EOF-819 - Remoção dos status code HTTP 423 e 429

---

dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPatchPortabilitiesPortabilityIdCancel_v1.0.0.csv
dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.2.yml
swagger-apis/credit-portability/index.html

feat(Credit Portability): EOF-820 - Alterar descrição do campo typeAdditionalInfo do endpoint de cancelamento

---

dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPatchPortabilitiesPortabilityIdCancel_v1.0.0.csv
dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.2.yml
swagger-apis/credit-portability/index.html

feat(Credit Portability): EOF-822 - Corrigir erros do Spectral

---

dictionary/creditPortabilityGetAccountData_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.2.yml

feat(Credit Portability): EOF-824 - PPC42 - Alterar o endpoint do pedido de portabilidade de crédito

---

dictionary/creditPortabilityGetAccountData_v1.0.0.csv
dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPatchPortabilitiesPortabilityIdCancel_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.2.yml

feat(Credit Portability): EOF-828 - Ajuste do campo hasFinancialAgent no endpoint [GET]/account-data na API de Portabilidade de Crédito

---

dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPatchPortabilitiesPortabilityIdCancel_v1.0.0.csv
dictionary/creditPortabilityPostPortabilitiesPortabilityIdPayment_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.3.yml

feat(Credit Portability): EOF-848 - PPC49 - Adequação das descrições de campos conforme código da STR exclusiva do OFB

---

dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPatchPortabilitiesPortabilityIdCancel_v1.0.0.csv
dictionary/creditPortabilityPostPortabilitiesPortabilityIdPayment_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.3.yml

feat(Credit Portability): EOF-849 - PPC50 - Incluir validação semântica na solicitação da portabilidade de crédito

---

dictionary/accountsGetAccountsAccountIdReservedBalances_v2.5.0.csv
dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.5.0.csv
dictionary/accountsGetAccountsAccountIdTransactions_v2.5.0.csv
swagger-apis/accounts/2.5.0.yml

feat(Accounts): EOF-856 - PDC444 - Alterar orientações de permissions necessárias

---

dictionary/accountsGetAccountsAccountIdReservedBalances_v2.5.0.csv
dictionary/accountsGetAccountsAccountIdTransactionsCurrent_v2.5.0.csv
dictionary/accountsGetAccountsAccountIdTransactions_v2.5.0.csv
swagger-apis/accounts/2.5.0.yml

feat(Accounts): EOF-859 - PDC450 - Adicionar campos complementares no novo endpoint para reserva de saldo

---

dictionary/creditPortabilityGetAccountData_v1.0.0.csv
dictionary/creditPortabilityGetCreditOperationsContratIdPortabilityEligibility_v1.0.0.csv
dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.3.yml

feat(Credit Portability): EOF-865 - PPC56 - remoção dos parâmetros de paginação da gestão de simultaneidade

---

dictionary/creditPortabilityGetAccountData_v1.0.0.csv
dictionary/creditPortabilityGetCreditOperationsContratIdPortabilityEligibility_v1.0.0.csv
dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-beta.3.yml

feat(Credit Portability): EOF-867 - Ajustar enum data.status no endpoint de consultar portabilidade

---

dictionary/creditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/creditPortabilityPostPortabilitiesPortabilityIdPayment_v1.0.0.csv
dictionary/creditPortabilityPostPortabilities_v1.0.0.csv
swagger-apis/credit-portability/1.0.0-rc.1.yml

feat(Credit Portability): EOF-922 - PPC66 - Ajustar campo portabilityId - maxLength, minLength e obrigatoriedade

---

dictionary/payrollCreditPortabilityGetAccountData_v1.0.0.csv
dictionary/payrollCreditPortabilityGetCreditOperationsContratIdPortabilityEligibility_v1.0.0.csv
dictionary/payrollCreditPortabilityGetPortabilitiesByPortabilityId_v1.0.0.csv
dictionary/payrollCreditPortabilityPatchPortabilitiesPortabilityIdCancel_v1.0.0.csv
dictionary/payrollCreditPortabilityPostPortabilities_v1.0.0.csv
swagger-apis/payroll-credit-portability/1.0.0-beta.1.yml

feat(Payroll Credit Portability): EOF-1023 - PPC80 - definição do endpoint para o cancelamento do pedido da portabilidade de crédito em andamento

---

dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.5.0.csv
dictionary/unarrangedAccountsOverdraftGetContracts_v2.5.0.csv
swagger-apis/unarranged-accounts-overdraft/2.5.0.yml

feat(Unarranged Accounts Overdraft): EOF-1028 - PDC488 - Adequar identificadores CNPJ ao novo padrão alfanumérico

---

dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.5.0.csv
dictionary/unarrangedAccountsOverdraftGetContracts_v2.5.0.csv
swagger-apis/unarranged-accounts-overdraft/2.5.0.yml

feat(Unarranged Accounts Overdraft): EOF-1029 - PDC489 - Adicionar novo header de versão

---

dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.5.0.csv
dictionary/unarrangedAccountsOverdraftGetContracts_v2.5.0.csv
swagger-apis/unarranged-accounts-overdraft/2.5.0.yml

feat(Unarranged Accounts Overdraft): EOF-1030 - PDC490 - Alterar maxLenght dos campos links

---

dictionary/unarrangedAccountsOverdraftGetContractsContractIdPayments_v2.5.0.csv
dictionary/unarrangedAccountsOverdraftGetContractsContractId_v2.5.0.csv
dictionary/unarrangedAccountsOverdraftGetContracts_v2.5.0.csv
swagger-apis/unarranged-accounts-overdraft/2.5.0.yml

feat(Unarranged Accounts Overdraft): EOF-1033 - PDC493 - Alterar a descrição de postFixedRate

---

dictionary/invoiceFinancingsGetContractsContractIdPayments_v2.4.0.csv
dictionary/invoiceFinancingsGetContractsContractIdScheduledInstalments_v2.4.0.csv
dictionary/invoiceFinancingsGetContractsContractIdWarranties_v2.4.0.csv
dictionary/invoiceFinancingsGetContractsContractId_v2.4.0.csv
dictionary/invoiceFinancingsGetContracts_v2.4.0.csv
swagger-apis/invoice-financings/2.4.0-beta.1.yml
swagger-apis/invoice-financings/index.html

feat(Invoice Financings): EOF-1047 - PDC502 -  Alterar a descrição da propriedade contractOutstandingBalance

---

dictionary/banktFixedIncomesGetInvestmentsInvestmentIdBalances_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentId_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestments_v1.1.0.csv
swagger-apis/bank-fixed-incomes/1.1.0-beta.1.yml

feat(Bank Fixed Incomes): EOF-1083- PDC507 - adicionar novo header de versão

---

dictionary/banktFixedIncomesGetInvestmentsInvestmentIdBalances_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentId_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestments_v1.1.0.csv
swagger-apis/bank-fixed-incomes/1.1.0-beta.1.yml

feat(Bank Fixed Incomes): EOF-1086 - PDC510 - alterar o pattern do campo brandName

---

dictionary/banktFixedIncomesGetInvestmentsInvestmentIdBalances_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentId_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestments_v1.1.0.csv
swagger-apis/bank-fixed-incomes/1.1.0-beta.1.yml

feat(Bank Fixed Incomes): EOF-1088 - PDC512 - ajustar o format dos campos links

---

dictionary/banktFixedIncomesGetInvestmentsInvestmentIdBalances_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentId_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestments_v1.1.0.csv
swagger-apis/bank-fixed-incomes/1.1.0-beta.1.yml

feat(Bank Fixed Incomes): EOF-1089 - PDC513 - alterar a descrição dos campos toTransactionDate e fromTransactionDate

---

dictionary/banktFixedIncomesGetInvestmentsInvestmentIdBalances_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentId_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestments_v1.1.0.csv
swagger-apis/bank-fixed-incomes/1.1.0-beta.1.yml

feat(Bank Fixed Incomes): EOF-1090 - PDC474 - ajuste da implementação das propostas

---

dictionary/treasureTitlesGetInvestmentsInvestmentIdBalances_v1.1.0.csv
dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactionsCurrent_v1.1.0.csv
dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactions_v1.1.0.csv
dictionary/treasureTitlesGetInvestmentsInvestmentId_v1.1.0.csv
dictionary/treasureTitlesGetInvestments_v1.1.0.csv
swagger-apis/treasure-titles/1.1.0-beta.1.yml
swagger-apis/treasure-titles/index.html

feat(Treasure Titles): EOF-1119 - PDC534 - adicionar novo header de versão

---

dictionary/treasureTitlesGetInvestmentsInvestmentIdBalances_v1.1.0.csv
dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactionsCurrent_v1.1.0.csv
dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactions_v1.1.0.csv
dictionary/treasureTitlesGetInvestmentsInvestmentId_v1.1.0.csv
dictionary/treasureTitlesGetInvestments_v1.1.0.csv
swagger-apis/treasure-titles/1.1.0-beta.1.yml
swagger-apis/treasure-titles/index.html

feat(Treasure Titles): EOF-1120 - PDC535 - ajustar o campo x-fapi-interaction-id

---

dictionary/treasureTitlesGetInvestmentsInvestmentIdBalances_v1.1.0.csv
dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactionsCurrent_v1.1.0.csv
dictionary/treasureTitlesGetInvestmentsInvestmentIdTransactions_v1.1.0.csv
dictionary/treasureTitlesGetInvestmentsInvestmentId_v1.1.0.csv
dictionary/treasureTitlesGetInvestments_v1.1.0.csv
swagger-apis/treasure-titles/1.1.0-beta.1.yml
swagger-apis/treasure-titles/index.html

feat(Treasure Titles): EOF-1122 - PDC537 - ajustar os campos postFixedIndexerPercentage, preFixedRate, remunerationTransactionRate

---

dictionary/fundsGetInvestmentsInvestmentIdBalances_v1.1.0.csv
dictionary/fundsGetInvestmentsInvestmentIdTransactionsCurrent_v1.1.0.csv
dictionary/fundsGetInvestmentsInvestmentIdTransactions_v1.1.0.csv
dictionary/fundsGetInvestmentsInvestmentId_v1.1.0.csv
dictionary/fundsGetInvestments_v1.1.0.csv
swagger-apis/funds/1.1.0-beta.1.yml
swagger-apis/funds/index.html

feat(Funds): EOF-1117 - PDC549 - ajustar o format dos campos Links

---

dictionary/creditFixedIncomesGetInvestmentsInvestmentIdBalances_v1.1.0.csv
dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.1.0.csv
dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.1.0.csv
dictionary/creditFixedIncomesGetInvestmentsInvestmentId_v1.1.0.csv
dictionary/creditFixedIncomesGetInvestments_v1.1.0.csv
swagger-apis/credit-fixed-incomes/1.1.0-beta.1.yml
swagger-apis/credit-fixed-incomes/1.1.0.yml
swagger-apis/credit-fixed-incomes/index.html

feat(Credit Fixed Incomes): EOF-1093 - PDC-517 - Adicionar novo header de versão

---

dictionary/creditFixedIncomesGetInvestmentsInvestmentIdBalances_v1.1.0.csv
dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.1.0.csv
dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.1.0.csv
dictionary/creditFixedIncomesGetInvestmentsInvestmentId_v1.1.0.csv
dictionary/creditFixedIncomesGetInvestments_v1.1.0.csv
swagger-apis/credit-fixed-incomes/1.1.0-beta.1.yml
swagger-apis/credit-fixed-incomes/1.1.0.yml
swagger-apis/credit-fixed-incomes/index.html

feat(Credit Fixed Incomes): EOF-1098 - PDC-522 - Ajustar a descrição dos campos toTransactionDate e fromTransactionDate

---

dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentId_v1.1.0.csv
swagger-apis/bank-fixed-incomes/1.1.0-beta.1.yml

feat(Bank Fixed Incomes): EOF-1137 - PDC632 - adicionar a description do campo postFixedIndexerPercentage

---

dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactionsCurrent_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.1.0.csv
dictionary/banktFixedIncomesGetInvestmentsInvestmentId_v1.1.0.csv
swagger-apis/bank-fixed-incomes/1.1.0-beta.1.yml

fix(Bank Fixed Incomes): EOF-1147 - Solicitação de ajustes

---

dictionary/resourcesGetResources_v3.1.0.csv
swagger-apis/resources/3.1.0-beta.1.yml
swagger-apis/resources/index.html

feat(Resources): EOF-1142 - PDC559 - alterar limite de extensão de parâmetros

---

dictionary/resourcesGetResources_v3.1.0.csv
swagger-apis/resources/3.1.0-beta.1.yml
swagger-apis/resources/index.html

feat(Resources): EOF-1144 - PDC624 - dicionar erro 422  

---

dictionary/creditFixedIncomesGetInvestmentsInvestmentIdTransactions_v1.1.0.csv
swagger-apis/credit-fixed-incomes/1.1.0-beta.1.yml

feat(Credit Fixed Incomes): EOF-1146 - PDC-629 - Inclusão de regra para exposição do PU em transferências de custódia

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdBills_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountId_v2.4.0.csv
dictionary/creditCardsGetAccounts_v2.4.0.csv
swagger-apis/credit-cards/2.4.0-beta.1.yml
swagger-apis/credit-cards/index.html

feat(Credit Cards): EOF-1157 - PDC561 - remover os campos totalPages e totalRecords nos retornos de erros

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdBills_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountId_v2.4.0.csv
dictionary/creditCardsGetAccounts_v2.4.0.csv
swagger-apis/credit-cards/2.4.0-beta.1.yml
swagger-apis/credit-cards/index.html

feat(Credit Cards): EOF-1165 - PDC569 - alterar descrição da lista de pagamentos de faturas

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdBills_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountId_v2.4.0.csv
dictionary/creditCardsGetAccounts_v2.4.0.csv
swagger-apis/credit-cards/2.4.0-beta.1.yml
swagger-apis/credit-cards/index.html

feat(Credit Cards): EOF-1166 - PDC570 - adicionar novo Enum para pagamento de fatura no endpoint de transactions e transactions-current

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdBills_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountId_v2.4.0.csv
dictionary/creditCardsGetAccounts_v2.4.0.csv
swagger-apis/credit-cards/2.4.0-beta.1.yml
swagger-apis/credit-cards/index.html

feat(Credit Cards): EOF-1167 - PDC575 - ajustar a descrição do campo billPostDate

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdBills_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountId_v2.4.0.csv
dictionary/creditCardsGetAccounts_v2.4.0.csv
swagger-apis/credit-cards/2.4.0-beta.1.yml
swagger-apis/credit-cards/index.html

feat(Credit Cards): EOF-1168 - PDC576 - ajustar a descrição do campo billId

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdBills_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountId_v2.4.0.csv
dictionary/creditCardsGetAccounts_v2.4.0.csv
swagger-apis/credit-cards/2.4.0-beta.1.yml
swagger-apis/credit-cards/index.html

feat(Credit Cards): EOF-1169 - PDC577 - ajustar o campo paymentMethod

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdBills_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountId_v2.4.0.csv
dictionary/creditCardsGetAccounts_v2.4.0.csv
swagger-apis/credit-cards/2.4.0-beta.1.yml
swagger-apis/credit-cards/index.html

feat(Credit Cards): EOF-1172 - PDC580 - ajustar a descrição do campo transactionId

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdBills_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountId_v2.4.0.csv
dictionary/creditCardsGetAccounts_v2.4.0.csv
swagger-apis/credit-cards/2.4.0-beta.1.yml
swagger-apis/credit-cards/index.html

feat(Credit Cards): EOF-1174 - PDC582 - ajustar listagem ordenada do endpoint transactions

---

dictionary/creditCardsGetAccountsCreditCardAccountIdBillsBillIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdBills_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdLimits_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactionsCurrent_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountIdTransactions_v2.4.0.csv
dictionary/creditCardsGetAccountsCreditCardAccountId_v2.4.0.csv
dictionary/creditCardsGetAccounts_v2.4.0.csv
swagger-apis/credit-cards/2.4.0-beta.1.yml
swagger-apis/credit-cards/index.html

feat(Credit Cards): EOF-1175 - PDC584 - ajustar a especificação conforme a IN 587
